package com.nikati.manage.modular.customer.email;

import com.nikati.manage.modular.customer.model.ServerInfo;
import org.springframework.stereotype.Component;

import javax.mail.*;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import java.io.File;
import java.util.Properties;

/**
 * @descripe：
 * @company：北京华如科技股份有限公司南京分公司
 * @author：zhoujinbing
 * @time：2026/6/4 23:49
 * @version：V1.0
 */
@Component
public class EmailSender {

    private String fromEmail = "755581919@qq.com";

    private String fromPassword = "ykxvdaiqwhsibbdb";


    public  void send(ServerInfo server, String toEmail, File qrFile) throws Exception {


        Properties props = new Properties();
        props.put("mail.smtp.host", "smtp.qq.com");
        props.put("mail.smtp.port", "587");
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");

        Session session = Session.getInstance(props, new Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(fromEmail, fromPassword);
            }
        });

        Message msg = new MimeMessage(session);
        msg.setFrom(new InternetAddress(fromEmail));
        msg.setRecipients(Message.RecipientType.TO, InternetAddress.parse(toEmail));
        msg.setSubject(server.getCustomerName() + ",Your QR Code");

        // ========== HTML正文 ==========
        MimeBodyPart htmlPart = new MimeBodyPart();

        String html = ""
                + "<div style='font-family:Arial;padding:20px;'>"
                + "<h2 style='color:#2b6cb0;'>Your QR Code is Ready 🎉</h2>"
                + "<p>Hello,</p>"
                + "<p>Your QR code has been successfully generated. Please find it attached to this email.</p>"
                + "<div style='padding:10px;background:#f5f5f5;border-radius:6px;margin:10px 0;'>"
                + "<b>Tips:</b><br>"
                + "• Save the attachment to your device<br>"
                + "• Scan it using any QR scanner<br>"
                + "</div>"
                + "<p style='color:#888;'>If you did not request this, please ignore this email.</p>"
                + "<hr>"
                + "<small>Auto-generated by System</small>"
                + "</div>";

        htmlPart.setContent(html, "text/html;charset=UTF-8");
//        MimeBodyPart textPart = new MimeBodyPart();
//        textPart.setText("Please find your QR code attached.");

        MimeBodyPart imagePart = new MimeBodyPart();
        imagePart.attachFile(qrFile);

        Multipart multipart = new MimeMultipart();
        multipart.addBodyPart(htmlPart);
        multipart.addBodyPart(imagePart);

        msg.setContent(multipart);

        Transport.send(msg);

        System.out.println("Email sent!");
    }


}